In [1]:
import numpy as np
def cv(x):
    #convert a list into a column vector
    return np.array([x]).T

In [6]:
def perceptron_origin(t, X, y):
    '''
    t: upper bound of iteration
    X: dataset
    y: corresponding label
    '''
    theta = cv([0]*len(X))
    n = 0
    for j in range(t):
        changed = False
        for i in range(len(y)):
            if (y[i]*(theta.T@cv(X[:, i]))).item() <= 0:
                theta = theta + y[i]*cv(X[:, i])
                n += 1
                changed = True
        if not changed:
            break
    return theta, n

In [4]:
x1 = [1,-1]
x2 = [0,1]
x3 = [-1.5,-1]
x1 = cv(x1)
x2 = cv(x2)
x3 = cv(x3)
X = np.concatenate((x1, x2, x3), axis=1)
y = cv([1, -1, 1])

In [7]:
perceptron_origin(50, X, y)

(array([[-0.5],
        [-2. ]]),
 2)

In [11]:
X = np.concatenate((x2, x3, x1), axis=1)
y = cv([-1, 1, 1])

In [12]:
perceptron_origin(50, X, y)

(array([[ 0.],
        [-1.]]),
 1)

In [13]:
x1 = [1,-1]
x2 = [0,1]

x1 = cv(x1)
x2 = cv(x2)
x3 = cv([-10, -1])
X = np.concatenate((x1, x2, x3), axis=1)
y = cv([1, -1, 1])

perceptron_origin(50, X, y)

(array([[-5],
        [-6]]),
 6)

In [15]:
X = np.concatenate((x2, x3, x1), axis=1)
y = cv([-1, 1, 1])
perceptron_origin(50, X, y)

(array([[ 0],
        [-1]]),
 1)

In [17]:
# 2.1
def perceptron_origin(t, X, y):
    '''
    t: upper bound of iteration
    X: dataset
    y: corresponding label
    '''
    theta = cv([1000, -1000])
    n = 0
    for j in range(t):
        changed = False
        for i in range(len(y)):
            if (y[i]*(theta.T@cv(X[:, i]))).item() <= 0:
                theta = theta + y[i]*cv(X[:, i])
                n += 1
                changed = True
        if not changed:
            break
    return theta, n

x1 = [1,-1]
x2 = [0,1]
x3 = [-1.5,-1]
x1 = cv(x1)
x2 = cv(x2)
x3 = cv(x3)
X = np.concatenate((x1, x2, x3), axis=1)
y = cv([1, -1, 1])

perceptron_origin(1000, X, y)

(array([[  769.],
        [-1154.]]),
 154)

In [18]:
# 2.2
def perceptron_origin(t, X, y):
    '''
    t: upper bound of iteration
    X: dataset
    y: corresponding label
    '''
    theta = cv([-1, 0])
    n = 0
    for j in range(t):
        changed = False
        for i in range(len(y)):
            if (y[i]*(theta.T@cv(X[:, i]))).item() <= 0:
                theta = theta + y[i]*cv(X[:, i])
                n += 1
                changed = True
        if not changed:
            break
    return theta, n

x1 = [1,-1]
x2 = [0,1]
x3 = [-1.5,-1]
x1 = cv(x1)
x2 = cv(x2)
x3 = cv(x3)
X = np.concatenate((x1, x2, x3), axis=1)
y = cv([1, -1, 1])

perceptron_origin(1000, X, y)

(array([[ 0.],
        [-1.]]),
 1)

In [26]:
# 3
def perceptron(t, X, y):
    '''
    t: upper bound of iteration
    X: dataset
    y: corresponding label
    '''
    theta = cv([0]*len(X))
    theta0 = 0
    n = 0
    for j in range(t):
        changed = False
        for i in range(len(y)):
            if (y[i]*(theta.T@cv(X[:, i]) + theta0)).item() <= 0:
                theta = theta + y[i]*cv(X[:, i])
                theta0 += y[i].item()
                n += 1
                changed = True
        if not changed:
            break
    return theta, theta0, n

In [27]:
x1 = cv([-3, 2])
x2 = cv([-1, 1])
x3 = cv([-1, -1])
x4 = cv([2, 2])
x5 = cv([1, -1])
X = np.concatenate([x1, x2, x3, x4, x5], axis=1)
y = cv([1, -1, -1, -1, -1])

perceptron(100, X, y)

(array([[-2],
        [ 0]]),
 -5,
 9)

In [1]:
# np.concatenate
import numpy as np
X = np.array([[2, 3, 9, 12, 1],
                  [5, 1, 6, 5, 1]])
D = np.array_split(X, 3, axis=1)
D

[array([[2, 3],
        [5, 1]]),
 array([[ 9, 12],
        [ 6,  5]]),
 array([[1],
        [1]])]

In [23]:
np.concatenate((D[:2]), axis=1)

array([[ 2,  3,  9, 12],
       [ 5,  1,  6,  5]])

In [2]:
np.concatenate((D[0], D[2]), axis=1)

array([[2, 3, 1],
       [5, 1, 1]])

In [18]:
np.concatenate((D[:1] + D[2:]), axis=1)

array([[2, 3, 1],
       [5, 1, 1]])

In [5]:
np.concatenate((D[:1], D[1+1:]), axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 2 and the array at index 1 has size 1

In [13]:
print(D[2], D[2].shape)
print(D[2:], len(D[2:])) # list has no shape property

[[1]
 [1]] (2, 1)
[array([[1],
       [1]])] 1


In [15]:
y = np.array([[1, -1, 1, -1]])
E = np.array_split(y, 3, axis=1)
np.concatenate((E[:1][0], E[1+1:][0]), axis=1)

array([[ 1, -1, -1]])