In [29]:
def score(data, labels, th, th0):
    return np.sum((np.sign(th.T.dot(data) + th0.T)) == labels, axis=1)

In [4]:
data = np.transpose(np.array([[1, 2], [1, 3], [2, 1], [1, -1], [2, -1]]))
labels = np.array([[-1, -1, +1, +1, +1]])

In [26]:
ths = np.array([[3, 4, 5], [4, 5, 6]])
th0s = np.array([[5, 6, 7]])
score(data, labels, ths, th0s)

array([3, 3, 3])

In [37]:
def best_separator(data, labels, ths, th0s):
    def score(data, labels, th, th0):
        return np.sum((np.sign(th.T.dot(data) + th0.T)) == labels, axis=1)
    index = np.argmax(score(data, labels, ths, th0s))
    return (index, np.array([ths[:, index]]).T, np.array([th0s[:, index]]))

In [38]:
best_separator(data, labels, ths, th0s)

(0,
 array([[3],
        [4]]),
 array([[5]]))