In [9]:
import numpy as np
def hinge_loss_grad(x, y, a):
    gradient_list = []
    for i in range(x.shape[0]):
        if y*a > 1:
            g = 0
        else:
            g = -y*x[i, :]
        gradient_list.append(g)
    return np.array(gradient_list).reshape(-1, 1)

In [10]:
hinge_loss_grad(np.array([[1],[-2]]), -1, 1.1)

array([[ 1],
       [-2]])

In [13]:
from math import exp
total = exp(-1) + exp(0) + exp(1)
li = [exp(-1)/total, exp(0)/total, exp(1)/total]
print(li)

[0.09003057317038046, 0.24472847105479767, 0.6652409557748219]


In [15]:
def sm(z):
    '''
    z: nx1
    '''
    a = []
    total = 0
    for i in range(z.shape[0]):
        total = total + exp(z[i,:])
        a.append(exp(z[i,:]))
    return np.array(a).reshape(-1, 1)/total

In [23]:
w = np.array([[1, -1, -2], [-1, 2, 1]])
x = np.array([[1, 1]]).T
y = np.array([[0, 1, 0]]).T
z = w.T@x
a = sm(z)
gradient_w = x@(a - y).T
print(gradient_w)

[[ 0.24472847 -0.33475904  0.09003057]
 [ 0.24472847 -0.33475904  0.09003057]]


In [30]:
from math import log
def NLL(a, y):
    loss = 0
    for i in range(a.shape[0]):
        loss = loss + y[i,:]*log(a[i,:])
    return -loss

In [31]:
eta = 0.5
w_new = w - eta*gradient_w
w_new.tolist()

[[0.8776357644726012, -0.8326204778874109, -2.04501528658519],
 [-1.1223642355273988, 2.167379522112589, 0.9549847134148097]]

In [32]:
z = w_new.T@x
a = sm(z)
a

array([[0.15918761],
       [0.77245284],
       [0.06835955]])

In [33]:
#3

# layer 1 weights
w_1 = np.array([[1, 0, -1, 0], [0, 1, 0, -1]])
w_1_bias = np.array([[-1, -1, -1, -1]]).T
# layer 2 weights
w_2 = np.array([[1, -1], [1, -1], [1, -1], [1, -1]])
w_2_bias = np.array([[0, 2]]).T

T  = np.matrix([[0.0 , 0.1 , 0.9 , 0.0],
[0.9 , 0.1 , 0.0 , 0.0],
[0.0 , 0.0 , 0.1 , 0.9],
[0.9 , 0.0 , 0.0 , 0.1]])
g = 0.9
r = np.matrix([0, 1., 0., 2.]).reshape(4, 1)

print(np.linalg.solve(np.eye(4) - g * T, r))

[[6.05288295]
 [6.48663207]
 [6.7519581 ]
 [7.58553317]]


In [50]:
x = np.array([3, 14]).reshape(-1, 1)
z_1 = w_1.T@x + w_1_bias
A = np.maximum(z_1, 0)
A.flatten()

array([ 2, 13,  0,  0])

In [61]:
z_2 = w_2.T@A + w_2_bias
A_2 = sm(z_2)
np.round(A_2)

array([[1.],
       [0.]])

In [73]:
x1 = np.array([0.5, 0.5]).reshape(-1, 1)
x2 = np.array([0, 2]).reshape(-1, 1)
x3 = np.array([-3, 0.5]).reshape(-1, 1)
X = np.concatenate((x1, x2, x3),axis=1)
Z = w_1.T@X + w_1_bias
A = np.maximum(Z, 0)
A.tolist()

[[0.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 2.0], [0.0, 0.0, 0.0]]

In [87]:
a = np.array([3, 0 , 0, 0]).reshape(-1, 1)
z_2 = w_2.T@a + w_2_bias
print(z_2)
a_2 = sm(z_2)
np.round(a_2)

[[ 3]
 [-1]]


array([[1.],
       [0.]])