In [2]:
def cv(value_list):
    '''
    Takes a list of numbers and returns a column vector:  n x 1
    '''
    return np.transpose(rv(value_list))

def rv(value_list):
    '''
    Takes a list of numbers and returns a row vector: 1 x n
    '''
    return np.array([value_list])

def y(x, th, th0):
    '''
    x is dimension d by 1
    th is dimension d by 1
    th0 is a scalar
    return a 1 by 1 matrix
    '''
    return np.dot(np.transpose(th), x) + th0

def positive(x, th, th0):
    '''
    x is dimension d by 1
    th is dimension d by 1
    th0 is dimension 1 by 1
    return 1 by 1 matrix of +1, 0, -1
    '''
    return np.sign(y(x, th, th0))

def score(data, labels, th, th0):
    '''
    data is dimension d by n
    labels is dimension 1 by n
    ths is dimension d by 1
    th0s is dimension 1 by 1
    return 1 by 1 matrix of integer indicating number of data points correct for
    each separator.
    '''
    return np.sum(positive(data, th, th0) == labels)

In [3]:
import numpy as np
data = np.array([[200, 800, 200, 800],
             [0.2,  0.2,  0.8,  0.8],
                [1, 1, 1, 1]])
labels = rv([-1, -1, 1, 1])
th = cv([0, 1, -0.5])

In [4]:
def margin(X, y, th):
    '''
    X: d by n matrix
    y: 1 by n rv
    th: d by 1 cv
    return scaler
    '''
    M = []
    for i in range(X.shape[1]):
        m = y[:, i]*(th.T@cv(X[:, i]))/np.linalg.norm(th)
        #print(m)
        M.append(m)
    return min(M).item()

In [18]:
margin(data, labels, th)

0.2683281572999747

In [5]:
def theotical_bound(X, y, th):
    gamma = margin(X, y, th)
    R = []
    for i in range(X.shape[1]):
        r = np.linalg.norm(cv(X[:, i]))
        R.append(r)
    return (max(R).item()/gamma)**2

In [24]:
theotical_bound(data, labels, th)

8888911.666666672

In [6]:
def perceptron(data, labels, params = {}, hook = None):
    T = params.get('T', 100)
    (d, n) = data.shape
    m = 0
    theta = np.zeros((d, 1)); theta_0 = np.zeros((1, 1))
    for t in range(T):
        for i in range(n):
            x = data[:,i:i+1]
            y = labels[:,i:i+1]
            if y * positive(x, theta, theta_0) <= 0.0:
                m += 1
                theta = theta + y * x
                theta_0 = theta_0 + y
                if hook: hook((theta, theta_0))
    return theta, theta_0

In [41]:
def perceptron_origin(data, labels, params = {}, hook = None):
    T = params.get('T', 100)
    (d, n) = data.shape
    m = 0
    theta = np.zeros((d, 1))
    for t in range(T):
        for i in range(n):
            x = data[:,i:i+1]
            y = labels[:,i:i+1]
            if y * positive(x, theta, 0) <= 0.0:
                m += 1
                theta = theta + y * x
                if hook: hook((theta, theta_0))
    return theta, m

In [45]:
# it took such a long time to run T = 8888911, therefore introduce changed:
def perceptron_origin(data, labels, params = {}, hook = None):
    T = params.get('T', 100)
    (d, n) = data.shape
    m = 0
    theta = np.zeros((d, 1))
    for t in range(T):
        changed = False
        for i in range(n):
            x = data[:,i:i+1]
            y = labels[:,i:i+1]
            if y * positive(x, theta, 0) <= 0.0:
                m += 1
                changed = True
                theta = theta + y * x
                if hook: hook((theta, theta_0))
        if not changed:
            break
    return theta, m

In [46]:
perceptron_origin(data, labels, params = {'T':8888911}, hook = None)

(array([[-2.000000e+02],
        [ 2.000068e+05],
        [-4.000000e+00]]),
 666696)

In [55]:
data = np.array([[200, 800, 200, 800],
             [0.2,  0.2,  0.8,  0.8]])
data_new = data*0.001
D = np.concatenate((data_new, rv([1, 1, 1, 1])), axis=0)
labels = rv([-1, -1, 1, 1])
th = cv([0, 1, -0.0005])

In [57]:
margin(D, labels, th)

0.00029999996250000706

In [58]:
m = 0.2683281572999747
m*(1+0.5**2)**0.5/((1000**2 + 0.5**2)**0.5)

0.000299999962500007

In [59]:
theotical_bound(D, labels, th)

18222233.88889067

In [60]:
18222233.88889067/8888911.666666672

2.049996059385297

In [61]:
data = np.array([[0.2, 0.8, 0.2, 0.8],
                [0.2,  0.2,  0.8,  0.8],
                [1, 1, 1, 1]])
labels = rv([-1, -1, 1, 1])
th = cv([0, 1, -0.5])
margin(data, labels, th)

0.2683281572999747

In [62]:
theotical_bound(data, labels, th)

31.666666666666686

In [63]:
perceptron_origin(data, labels, params = {'T':31}, hook = None)

(array([[-0.2],
        [ 1.6],
        [-1. ]]),
 7)

In [3]:
import numpy as np
data = np.array([[2, 3,  4,  5]])
labels = rv([1, 1, -1, -1])
print(data.shape)
print(labels.shape)

(1, 4)
(1, 4)


In [7]:
perceptron(data, labels, params = {}, hook = None)

(array([[-2.]]), array([[7.]]))

In [15]:
def one_hot(x, k):
    vec = np.zeros((k, 1))
    vec[x-1] = 1
    return vec

In [16]:
one_hot(3, 7)

array([[0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [24]:
res = np.zeros((6, 1))
for i in range(4):
    x = data[:, i].item()
    r = one_hot(x, 6)
    res = np.append(res, r, axis=1)
data = res[:, 1:]
data

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [31]:
th, th0 = perceptron(data, labels, params = {}, hook = None)

In [34]:
print(th.flatten(), th0)

[ 0.  2.  1. -2. -1.  0.] [[0.]]


In [42]:
(th.T@one_hot(1, 6)+th0)/np.linalg.norm(th)

array([[0.]])

In [45]:
data =   np.array([[1, 2, 3, 4, 5, 6]])
labels = rv([1, 1, -1, -1, 1, 1])

res = np.zeros((6, 1))
for i in range(data.shape[1]):
    x = data[:, i].item()
    r = one_hot(x, 6)
    res = np.append(res, r, axis=1)
data_oh = res[:, 1:]

data_oh

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [46]:
perceptron(data_oh, labels, params = {}, hook = None)

(array([[ 1.],
        [ 1.],
        [-2.],
        [-2.],
        [ 1.],
        [ 1.]]),
 array([[0.]]))

In [49]:
li = []
for i in [1, 10, 20, 30, 40, 50]:
    res = (i + 2)*(i + 1)/2
    li.append(int(res))
li

[3, 66, 231, 496, 861, 1326]